---
title: "Peptide Analysis"
output: html_notebook
---

```{r}
install.packages("dplyr")
install.packages("tidyverse")
```

```{r}
library("dplyr")
library(stringr)
library(tidyverse)
library(ggplot2)
```

```{r}
# Nominal proteins w/ quantitites within the UPS standards
ups_ref <- read.csv("UPS Proteins.tsv",
                  header = TRUE) %>%
  select(ups_protein = X...UniProt.Accession.Number,
         ups1_amount = UPS1.Amount..fmol.,
         ups2_amount = UPS2.Amount..fmol.) %>%
  mutate(ups2_amount = gsub(",","",ups2_amount)) %>%
  mutate(ups1_amount = gsub(",","",ups1_amount))
row.names(ups_ref) = ups_ref$ups_protein

# Replicate 4 of the UPS1 data 
ups1_raw <- read.table("Data/UPS/UPS1/UPS1_04-Peptide_Shaker_on_data_24__Peptide_Report.tabular",
                   sep = "\t", comment.char="", header = TRUE) %>%
  select(ups1_protein = Protein.s.,
         Sequence,
         ups1_validated_psms = X.Validated.PSMs)

# Filters the dataset to keep only UPS proteins
ups1 <- filter(ups1_raw, grepl("ups", ups1_protein))

# Replicate 4 of the UPS2 data
ups2_raw <- read.table("Data/UPS/UPS2/UPS2_04-Peptide_Shaker_on_data_28__Peptide_Report.tabular",
                   sep = "\t", comment.char="", header = TRUE) %>%
  select(proteins = Protein.s.,
         Sequence,
         ups2_validated_psms = X.Validated.PSMs)

# Filters the dataset to keep only UPS proteins
ups2 <- filter(ups2_raw, grepl("ups", proteins)) %>%
  # Extracts the UPS protein's identifier
  extract(proteins,'ups_protein', regex = '.*([A-Z][0-9]+)ups.*', remove = FALSE) %>%
  # Matches the extracted ID to the UPS_ref df to obtain the nominal fmol amount
  mutate(amount = ups_ref[ups_protein,]$ups2_amount)

ups_proteins <- unique(ups2$ups_protein)
grouped_ups <- data.frame(amount = numeric(length(ups_proteins)),
                          validated_psms = numeric(length(ups_proteins)))

for (i in seq_along(ups_proteins) ){
  grouped_ups$amount[i] <- ups_ref[ups_proteins[i],]$ups2_amount
  grouped_ups$validated_psms[i] <- sum(ups2[which(ups2$ups_protein == ups_proteins[i]),]$ups2_validated_psms)
  #grouped_ups <- rbind(grouped_ups, data.frame(protein, "asdf","asdf"))
}
row.names(grouped_ups) = ups_proteins

ggplot(grouped_ups, aes(x=amount, y=validated_psms)) + 
  geom_point() +
  geom_text(label=rownames(grouped_ups), position = position_nudge(x = .2, y =.2))
```



Number of peptides found in the UPS datasets:
```{r}
paste('UPS peptides found in UPS1:', nrow(ups1))
paste('Total number of peptides found in UPS1:', nrow(ups1_raw))
```
```{r}
paste('UPS peptides found in UPS2:', nrow(ups2))
paste('Total number of peptides found in UPS2:', nrow(ups2_raw))
```


Extracts the fmol amount of UPS2 protein

```{r}
ups_ref[str_match('LALBA_HUMAN; P00709ups','.*(P[0-9]+)ups,*')[2],]$ups2_amount

```




